FROM ubuntu:15.10
MAINTAINER Fabien Dubosson <fabien.dubosson@gmail.com>

# Set locale
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  

# Create `emacs` user
RUN useradd -ms /bin/bash emacs
ENV HOME /home/emacs

# Needed by `exec-path-from-shell`
ENV SHELL /bin/bash

# Update the system
RUN apt-get update && apt-get upgrade -y

# Install needed packages
RUN apt-get install -y git

# Install emacs
RUN apt-get install -y emacs

# Cleanup
RUN rm -rf /var/lib/apt/lists/* 

USER emacs
WORKDIR /home/emacs

ENTRYPOINT ["emacs"]
